steps:
  # ① ソースコードを元に、Dockerイメージ（アプリのパッケージ）を自動で組み立てて保存する
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - 'gcr.io/$PROJECT_ID/nimmt-board-game'
      - '--builder'
      - 'gcr.io/buildpacks/builder:v1'

  # ② 組み立てたパッケージを、Cloud Run（本番環境）へガツンとデプロイする
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nimmt-board-game' # 以前作ったCloud Runのサービス名に合わせてね
      - '--image'
      - 'gcr.io/$PROJECT_ID/nimmt-board-game'
      - '--region'
      - 'us-east1' # 以前のURLに「east1」とあったので、おそらくus-east1なのだ！
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY